-- NTF-02 알림 목록 조회
-- 사용자는 본인의 알림 내역을 조회할 수 있다.

SELECT 
	NS.NOTIFICATION_CONTENT AS '알림내용', 
	NH.NOTIFICATION_CREATED_AT AS '알림시간'
	FROM NOTIFICATION_SEND NS 
	JOIN NOTIFICATION_HISTORY NH ON NS.NOTIFICATION_SEND_CODE = NH.NOTIFICATION_SEND_CODE
	WHERE NH.USER_CODE = 10; 