-- MEM-17 : 댓글 신고 조회
-- 관리자는 사용자가 신고 요청한 댓글 조회

-- VIDW 테이블 삭제
-- DROP VIEW COMPLAINT_COMMENT_VIEW;

-- 댓글 신고 조회 VIDW TABLE 생성
CREATE VIEW COMPLAINT_COMMENT_VIEW AS
SELECT R.NICK_NAME  AS COMPLAINTED_USER -- 신고 당한 사람의 닉네임
	 , BR.NICK_NAME  AS REPORTER	-- 신고한 사람의 닉네임
	 , DATE_FORMAT(CP.COMPLAIN_DATE , '%Y년%m월%d일% %T') AS COMPLAIN_DATE -- 신고일
	 , CM.COMMENTS_CONTENT AS  -- 신고 당한 댓글 내용
	 , B.BOARD_TITLE AS 	-- 신고 당한 댓글의 게시글
	 , DATE_FORMAT(CM.COMMENTS_CREATED_AT , '%Y년%m월%d일% %T')  AS COMMENTS_CREATED_AT -- 신고 당한 댓글을 작성한 날짜
  FROM COMPLAINT CP
  JOIN COMMENTS CM ON CP.COMPLAINT_NUM = CM.COMMENTS_CODE
  JOIN MEMBER R ON CP.USER_CODE = R.USER_CODE
  JOIN BOARD B USING(BOARD_CODE)
  JOIN MEMBER BR ON CP.BLACK_CODE = BR.USER_CODE
 WHERE CP.COMMON_CODE = 'c32';

-- SELECT문
SELECT ROW_NUMBER() OVER(ORDER BY CC.COMMENTS_CREATED_AT DESC) AS NO
	  , CC.*
  FROM COMPLAINT_COMMENT_VIEW CC
 ORDER BY NO ASC
 LIMIT 10 OFFSET 0;