-- MEM-19 : 사용자 신고 목록 조회
-- 관리자는 신고 당한 사람과 신고 한 사람의 목록을 조회

-- VIDW 테이블 삭제
-- DROP VIEW COMPLAINT_USER_VIEW;

-- 사용자 신고 조회 VIDW TABLE 생성
CREATE VIEW COMPLAINT_USER_VIEW AS
SELECT R.NICK_NAME  AS COMPLAINTED_USER -- 신고 당한 사람의 닉네임
	 , BR.NICK_NAME  AS REPORTER	-- 신고한 사람의 닉네임
	 , DATE_FORMAT(CP.COMPLAIN_DATE , '%Y년%m월%d일% %T')  AS COMPLAIN_DATE -- 신고일
	 , CM.COMMON_NAME   -- 댓글/게시글 구분
  FROM COMPLAINT CP
  JOIN MEMBER R ON CP.USER_CODE = R.USER_CODE
  JOIN MEMBER BR ON CP.BLACK_CODE = BR.USER_CODE
  JOIN COMMON CM USING(COMMON_CODE);

-- SELECT문
 SELECT ROW_NUMBER() OVER(ORDER BY CU.COMPLAIN_DATE DESC) AS NO  -- 번호
	 , CU.*
  FROM COMPLAINT_USER_VIEW CU
 ORDER BY NO ASC
 LIMIT 10 OFFSET 0;

